### ISSUE TITLE
Does the Solid example work with Vite 5 since I get an issue loading the pdf.worker.js file?

### ISSUE THREAD

**Issue by Dima-369** [pdfslick/pdfslick#32] opened 2024-05-11 19:36 UTC
I tried out the Solid.js code example and I get this error. Is this because I use `Vite` with it? Is there a workaround to this?

![CleanShot 2024-05-11 at 21 27 04](https://github.com/pdfslick/pdfslick/assets/15002298/65c2e478-1342-4a1c-86ea-4475fc9de9a0)

I checked the file paths and http://localhost:5173/node_modules/.vite/deps/pdfjs-dist/build/pdf.worker.js does not exist for me. There isn't anything in `deps` actually related to it.

If I run `pnpm i pdfjs-dist`, I will get the `node_modules/pdfjs-dist/build/pdf.worker.mjs` file (but it is `.mjs` and not `.js`?) and I wondered if I just need to link this file, but I am not sure how.

**Comment by van100j** [comment] 2024-05-15 10:13
Hi @Dima-369,

Here's an [example PDFSlick project for Solid](https://github.com/van100j/solid-pdfslick) created with Vite. Seems to be working fine locally, but also when deployed at https://solid-pdfslick.stojkov.me/

Can you check which `pdfjs-dist` version you're using? That `.mjs` extension hints you might be using version 4.x.x (PDFSlick uses version 3)

**Comment by Dima-369** [comment] 2024-05-15 22:10
Hey, thanks for the answer! I tried with the following steps:

```bash
git clone https://github.com/van100j/solid-pdfslick
cd solid-pdfslick
pnpm i
pnpm run dev
```

Then I see the exact same error as above, supposedly because `pdfjs-dist` is not automatically installed? Or at least, not in the directory as noted above. So, I downloaded it like this from https://github.com/mozilla/pdfjs-dist (is it fine from this repository?) which seems to be version 3.

```bash
git clone git@github.com:mozilla/pdfjs-dist.git node_modules/.vite/deps/
```

I tested this, but then I always see this error. What am I missing? I can not find any info in the README about `pdfjs-dist` setup. I also tried the versions from https://github.com/mozilla/pdf.js/releases?page=2 

![CleanShot 2024-05-16 at 00 02 23](https://github.com/pdfslick/pdfslick/assets/15002298/814111a5-8f2c-4f3d-8993-2147bb9ef77e)

**Comment by van100j** [comment] 2024-05-15 22:25
Hey @Dima-369 

I'm actually able to reproduce your error — when I run the exact commands as you are (with `pnpm` instead of `npm`) I'm also experiencing the same issues. Running the commands with `npm` seems fine though.

Personanly I'm a `npm` user, so if you could use `npm` that'd be great. In the meantime I'll try to investigate what's really happening with `pnpm`, although it seems kinda weird because we're being explicit with the [`pdfjs-dist` version](https://github.com/pdfslick/pdfslick/blob/main/packages/core/package.json#L49)

**Comment by Dima-369** [comment] 2024-05-16 20:23
> Running the commands with npm seems fine though.

Indeed, I can confirm that! Thanks for the hint.

I was able to fix with `pnpm`. You just need to add `"pdfjs-dist": "3.11.174"` into the `dependencies` in `package.json` - then it works in both `npm` and `pnpm`.

Do you want to adjust the repository with this, maybe?

**Comment by van100j** [comment] 2024-05-16 20:37
Thanks @Dima-369! You're right, we actually need `pdfjs-dist": "3.11.174"`.

Up for submitting a PR with this update?

**Comment by Dima-369** [comment] 2024-05-16 20:53
> Up for submitting a PR with this update?

Sure. I will do it in this repo and in https://github.com/van100j/solid-pdfslick

**Comment by van100j** [comment] 2024-05-16 22:14
@Dima-369 ended up updating the [`pdfjs-dist` version in the core package](https://github.com/pdfslick/pdfslick/pull/34/files#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7R49). Solid and other projects should work fine with `pnpm` too, I've just tried it out with the example at https://github.com/van100j/solid-pdfslick and the new version, seems ok.

Closing this issue, let me know if you experience further issues with this or anything else. 

Thanks again for reporting and soving this!

**Closed by van100j** 2024-05-16 22:14 UTC

**Comment by meseven** [comment] 2025-01-29 12:35
Hey guys,
It seems to work with NPM but still not with PNPM. 
When I try to run this example with pnpm, I get the following error. How can I solve it?

<img width="758" alt="Image" src="https://github.com/user-attachments/assets/1cb31ba3-eeb0-4e72-9c63-6ec9c340af8e" />

**Comment by meseven** [comment] 2025-01-29 19:51
Okay, i fixed it with this vite config below.

```javascript
{
  // ...other configs
  optimizeDeps: {
    exclude: ['@pdfslick/core'],
  }
}
```

**Comment by van100j** [comment] 2025-01-30 16:10
@meseven out of curiosity, was this also a SolidJS project you were experiencing this issue on?

**Comment by Dentling** [comment] 2025-03-31 11:48
> Okay, i fixed it with this vite config below.
> 
> {
>   // ...other configs
>   optimizeDeps: {
>     exclude: ['@pdfslick/core'],
>   }
> }

Had the same issue with React and Vite.
Excluding it like this solved the issue.

**Comment by Fallstop** [comment] 2025-04-03 04:36
Same issue when switching to PNPM on a Svelte app; simply installing `pdfjs-dist` as a direct dev-dependency like Solid worked for me. Worth adding this as a note to the Docs?

**Comment by van100j** [comment] 2025-04-03 20:09
`pdfjs-dist` is a PDFSlick dependency. What exactly is the issue, and how are you solving it?
